CREATE DATABASE SISCMEX;

USE SISCMEX;

CREATE TABLE DOCUMENTO_ENTRADA

    (cd_nota_fiscal INTEGER  NOT NULL ,

    cd_cnpj VARCHAR (30));

ALTER TABLE DOCUMENTO_ENTRADA

    ADD CONSTRAINT DOCUMENTO_ENTRADA_PK PRIMARY KEY ( cd_nota_fiscal ) ;

CREATE TABLE ENTRADA_MATERIAL

    (cd_material INTEGER  NOT NULL ,

    qt_material INTEGER ,

    cd_nota_fiscal INTEGER  NOT NULL );

ALTER TABLE ENTRADA_MATERIAL

    ADD CONSTRAINT ENTRADA_MATERIAL_PK PRIMARY KEY ( cd_material, cd_nota_fiscal ) ;

CREATE TABLE FORNECEDOR

    (cd_cnpj VARCHAR (30)  NOT NULL ,

    nm_razao_social VARCHAR (30) ,

    nm_endereco VARCHAR (50)  NOT NULL ,

    nm_telefone VARCHAR (20) ,

    nm_email VARCHAR (70) ,

    nm_ramo_atividade VARCHAR (30) );

ALTER TABLE FORNECEDOR

    ADD CONSTRAINT FORNECEDOR_PK PRIMARY KEY ( cd_cnpj ) ;

ALTER TABLE FORNECEDOR

    ADD CONSTRAINT FORNECEDOR__UN UNIQUE ( nm_email ) ;

CREATE TABLE MATERIAL

    (cd_material INTEGER  NOT NULL ,

    nm_material VARCHAR (30) ,

    nm_descricao VARCHAR (50) ,

    qt_material INTEGER ,

    nm_tipo VARCHAR (30) ,

    sg_unidade VARCHAR (5) );

ALTER TABLE MATERIAL

    ADD CONSTRAINT MATERIAL_PK PRIMARY KEY ( cd_material ) ;

CREATE TABLE SAIDA_MATERIAL

    (cd_solicitacao INTEGER  NOT NULL ,

    cd_material INTEGER  NOT NULL ,

    qt_material INTEGER );

ALTER TABLE SAIDA_MATERIAL

    ADD CONSTRAINT SAIDA_MATERIAL_PK PRIMARY KEY ( cd_solicitacao, cd_material ) ;

CREATE TABLE SETOR

    (cd_setor INTEGER  NOT NULL ,

    nm_setor NVARCHAR (30) );

ALTER TABLE SETOR

    ADD CONSTRAINT SETOR_PK PRIMARY KEY ( cd_setor ) ;

ALTER TABLE SETOR

    ADD CONSTRAINT SETOR__UN UNIQUE ( cd_setor ) ;

CREATE TABLE SOLICITACAO_MATERIAL

    (cd_solicitacao INTEGER  NOT NULL ,

    cd_setor INTEGER  NOT NULL );

ALTER TABLE SOLICITACAO_MATERIAL

    ADD CONSTRAINT SOLICITACAO_MATERIAL_PK PRIMARY KEY ( cd_solicitacao ) ;

CREATE TABLE USUARIO

    (cd_identidade INTEGER  NOT NULL ,

    nm_usuario VARCHAR (30) ,

    nm_guerra VARCHAR (15) ,

    nm_senha VARCHAR (8) ,

    nm_acesso VARCHAR (30) ,

    cd_setor INTEGER );

ALTER TABLE USUARIO

    ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( cd_identidade ) ;

ALTER TABLE DOCUMENTO_ENTRADA

    ADD CONSTRAINT DOCENTRADA_FORNECEDOR_FK FOREIGN KEY

    (cd_cnpj) REFERENCES FORNECEDOR  (cd_cnpj) ;

ALTER TABLE ENTRADA_MATERIAL

    ADD CONSTRAINT ENTRADA_DOCUMENTO_ENTRADA_FK FOREIGN KEY

    (cd_nota_fiscal) REFERENCES DOCUMENTO_ENTRADA (cd_nota_fiscal);

ALTER TABLE ENTRADA_MATERIAL

    ADD CONSTRAINT ENTRADA_MATERIAL_FK FOREIGN KEY

    (cd_material) REFERENCES MATERIAL (cd_material);

ALTER TABLE SAIDA_MATERIAL

    ADD CONSTRAINT SAIDA_MATERIAL_FK FOREIGN KEY

    (cd_material) REFERENCES MATERIAL (cd_material);

ALTER TABLE SAIDA_MATERIAL

    ADD CONSTRAINT SAIDA_SOLICITACAO_MATERIAL_FK FOREIGN KEY

    (cd_solicitacao) REFERENCES SOLICITACAO_MATERIAL (cd_solicitacao);

ALTER TABLE SOLICITACAO_MATERIAL

    ADD CONSTRAINT SOLICITACAO_SETOR_FK FOREIGN KEY

    (cd_setor) REFERENCES SETOR (cd_setor);

ALTER TABLE USUARIO

    ADD CONSTRAINT USUARIO_SETOR_FK FOREIGN KEY
    (cd_setor) REFERENCES SETOR (cd_setor);